version: '3.8'
services:
  db:
    image: postgres:16.2-alpine
    container_name: database
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_DB=fss
    ports:
      - 5432:5432
    secrets:
      - db_password


volumes:
  db_data:

secrets:
  db_password:
    file: db_password.txt